"""Auto-generated inventory docs: one file per group (skills, mcps, hooks, agents), one
line per item, derived from the live config + each item's own source. Never hand-edited.

Wired into the reconciler: `apply` rewrites the docs, `verify` flags drift. So the docs
stay correct without anyone remembering to update them — the determinism protocol applied
to documentation. Writes into <config>/docs/. Stdlib only.
"""
from __future__ import annotations

import re
from pathlib import Path

from core.targets import Json, Link, Merge
from core.util import Ctx

GROUPS = ("skills", "mcps", "hooks", "agents")
HEADER = ("<!-- AUTO-GENERATED by `agentsync apply` — do not edit; changes are overwritten.\n"
          "     Regenerate: `agentsync docs`. Drift is caught by `agentsync verify`. -->\n")


def _oneline(s: str, limit: int = 200) -> str:
    s = " ".join((s or "").split())
    return s if len(s) <= limit else s[: limit - 1].rstrip() + "…"


def fm_description(md_path: Path) -> str:
    """Pull `description:` out of a markdown file's YAML frontmatter (handles plain,
    quoted, and folded `>`/`|` block scalars), collapsed to one line."""
    try:
        text = md_path.read_text()
    except Exception:
        return ""
    if not text.startswith("---"):
        return ""
    end = text.find("\n---", 3)
    fm = text[3:end] if end > 0 else text
    lines = fm.splitlines()
    for i, line in enumerate(lines):
        m = re.match(r"\s*description\s*:\s*(.*)", line)
        if not m:
            continue
        val = m.group(1).strip()
        if val in ("", ">", "|", ">-", "|-", ">+", "|+"):  # block scalar -> gather indented
            base = len(line) - len(line.lstrip())
            buf = []
            for nl in lines[i + 1:]:
                if nl.strip() == "":
                    continue
                if len(nl) - len(nl.lstrip()) > base:
                    buf.append(nl.strip())
                else:
                    break
            return _oneline(" ".join(buf))
        return _oneline(val.strip("\"'"))
    return ""


def _script_summary(path: str) -> str:
    """First comment line of a shell/js script as its summary."""
    p = Path(path)
    if not p.exists():
        return ""
    for line in p.read_text().splitlines():
        s = line.strip()
        if s.startswith("#!") or s == "":
            continue
        if s.startswith("#"):
            return _oneline(s.lstrip("#").strip(), 140)
        if s.startswith("//"):
            return _oneline(s.lstrip("/").strip(), 140)
        break
    return ""

_CMD_HINTS = {
    "rtk hook": "rtk — token-killer CLI proxy (rewrites commands to compact output)",
    "claude-notify": "desktop notification",
    "setup-reminders": "injects environment setup reminders",
}


def _cmd_summary(cmd: str) -> str:
    for k, v in _CMD_HINTS.items():
        if k in cmd:
            return v
    path = re.search(r'(/[^\s"]+\.(?:sh|js))', cmd)
    if path:
        return _script_summary(path.group(1)) or _oneline(cmd, 100)
    return _oneline(cmd, 100)


# ----- per-group renderers (return the markdown body) --------------------------------

def _skills(ctx: Ctx) -> str:
    rows = []
    for name in sorted(ctx.skills):
        tier = ctx.skills[name]
        src = ctx.skill_paths.get(name)
        desc = fm_description(Path(src) / "SKILL.md") if src else ""
        rows.append(f"- **{name}** (`{tier}`) — {desc or '_no description_'}")
    return f"{len(rows)} skills.\n\n" + "\n".join(rows) + "\n"


def _mcps(ctx: Ctx) -> str:
    rows = []
    for name in sorted(ctx.servers):
        s = ctx.servers[name]
        endpoint = s.get("url") or " ".join([s.get("command", "")] + s.get("args", []))
        desc = s.get("description") or f"{s.get('transport', '?')} · {endpoint}"
        rows.append(f"- **{name}** — {_oneline(desc, 160)}")
    return f"{len(rows)} MCP servers.\n\n" + "\n".join(rows) + "\n"


def _hooks(ctx: Ctx) -> str:
    from core.adapters import ADAPTERS
    wanted = ctx.profile.get("harnesses", list(ADAPTERS))
    blocks = []
    for hname in wanted:
        rows = []
        for t in ADAPTERS[hname].targets(ctx):
            if isinstance(t, Merge):
                for spec in t.hooks:  # determinism hooks
                    rows.append(f"- `{spec.event}` — {_cmd_summary(spec.command)} _(determinism)_")
                for ev, groups in t.extra_hooks.items():  # user hooks (overrides)
                    for g in groups:
                        cmds = ([g["command"]] if "command" in g else
                                [g["bash"]] if "bash" in g else
                                [h.get("command", "") for h in g.get("hooks", [])])
                        for c in cmds:
                            rows.append(f"- `{ev}` — {_cmd_summary(c)}")
            elif isinstance(t, Json) and isinstance(t.obj, dict) and "hooks" in t.obj:
                for ev, groups in t.obj["hooks"].items():  # hook-file target (e.g. VS Code)
                    for g in groups:
                        for h in g.get("hooks", []):
                            cmd = h.get("command", "")
                            det = " _(determinism)_" if re.search(r"(guard-commit|session-nudge|prompt-context)\.sh", cmd) else ""
                            rows.append(f"- `{ev}` — {_cmd_summary(cmd)}{det}")
            elif isinstance(t, Link) and t.path.name == "determinism.js":
                rows.append(f"- `plugin` — {_script_summary(str(t.src))} _(determinism)_")
        if rows:
            blocks.append(f"### {hname}\n" + "\n".join(rows))
    return "Hooks wired per harness (determinism gate + your custom hooks).\n\n" + "\n\n".join(blocks) + "\n"


def _agent_dirs(ctx: Ctx):
    dirs = [Path.home() / ".claude" / "agents"]
    for ov in ctx.overrides.values():
        for key in ("chat.agentFilesLocations", "chat.modeFilesLocations"):
            for p in (ov.get(key) or {}):
                dirs.append(Path(p).expanduser())
    seen, out = set(), []
    for d in dirs:
        if d not in seen and d.is_dir():
            seen.add(d); out.append(d)
    return out


def _agents(ctx: Ctx) -> str:
    found = {}
    for d in _agent_dirs(ctx):
        for f in sorted(d.glob("*.md")):
            if f.name.startswith("["):  # template
                continue
            name = re.sub(r"\.(agent|chatmode)$", "", f.stem)
            found.setdefault(name, fm_description(f))
    rows = [f"- **{n}** — {d or '_no description_'}" for n, d in sorted(found.items())]
    return f"{len(rows)} agents.\n\n" + ("\n".join(rows) + "\n" if rows else "_none found_\n")


RENDERERS = {"skills": _skills, "mcps": _mcps, "hooks": _hooks, "agents": _agents}


def _content(group: str, ctx: Ctx) -> str:
    title = {"skills": "Skills", "mcps": "MCP servers", "hooks": "Hooks", "agents": "Agents"}[group]
    return f"{HEADER}\n# {title}\n\n{RENDERERS[group](ctx)}"


def generate(ctx: Ctx, write: bool):
    """Returns (changed, drift). write=True rewrites; write=False reports drift only."""
    docs = ctx.config / "docs"
    changed, drift = [], False
    for group in GROUPS:
        path = docs / f"{group}.md"
        new = _content(group, ctx)
        cur = path.read_text() if path.exists() else None
        if cur == new:
            continue
        drift = True
        changed.append(group)
        if write:
            docs.mkdir(parents=True, exist_ok=True)
            path.write_text(new)
    return changed, drift
